### ISSUE TITLE
What gives you inspiration?

### ISSUE THREAD

**Issue by flatkingcreative** [helenvholmes/ama#2]
This is a question based mainly on your site and how it looks but in general too - Where do you get your inspiration from how do you turn it from ideas to digital?

**Comment by helenvholmes** [comment]
[My site, for anyone else who's curious.](http://helenvholmes.com/)

I gave a long-winded, rambly version of this to a friend recently. I'll try and do a better job of that for you.

I like to start outwards in: gather information from the _least_ technological inspiration sources first, moving toward more and more tech inspiration as I get closer to finishing. I don't do this for _every_ project, but for things like my portfolio this is how I like to start. This is a thing I learned in school and still find I get the most interesting designs when I give myself the space to think this way.

1. **Gather inspiration from life.** Meaning, literally, go take walks. Hang out by pools. Have conversations with friends about what you want to build. Try and lock down _moods_ and _feelings_. If you have a clearly articulated problem and sense of feeling you want to provoke, you're ready to start sketching.
2. **Create a mood board.** This will help convey that mood to other people, and to yourself. I like to this because it forces me to curate really heavily. I use Pinterest to create mood boards, here are a few examples:

[undetermined 2 currently](https://www.pinterest.com/helenvholmes/undetermined-2-currently/)
[undetermined 1 currently](https://www.pinterest.com/helenvholmes/undetermined-1-currently/)
[january 2014 currently (this one launched v.3 of my portfolio)](https://www.pinterest.com/helenvholmes/january-2014-currently/)

3. **Take sketches and mood board and dump them all into a computer file.** The specifics from here on out depend on what tools you're most comfortable with—I use [Sketch](https://www.sketchapp.com/) for this kind of work, for example—but the idea is to start building a color palette and some general grids using the photos you're pulled together as inspiration.
4. **Share it with people.** [Stuff often doesn't come out fully-baked. I am really bad with typography, for example. ([Which is kind of hilarious considering how much I care about it](http://helenvholmes.com/writing/type-is-your-right).) Having other people look over for things you know you're weak in is the same as a code review, or having someone edit an essay. You should do this, you should have friends do this, you should do this again. Play until you feel really happy with it. Know you're not going to get it right the first time. Take others' advice with a grain of salt based on your vision for the project.
