### ISSUE TITLE
Pen and Paper

### ISSUE THREAD

**Issue by charlespeters** [helenvholmes/ama#3]
what are you favorite pens and paper/notebooks?

**Comment by helenvholmes** [comment]
I did a [tweet thread](https://twitter.com/helenvholmes/status/695318608407195648) about this once! But it's the nature of Twitter for things to slowly get buried in the sands of time, so I'll transfer that info here.

I have a big ol' bag of pens I cart around with me everywhere that's filled with [all sorts of weird stuff, including pens](https://medium.com/@helenvholmes/whats-in-my-pencil-case-january-16th-2017-e80e260cab5b#.u9dh21p7c). I like having options based on how I'm writing (I have three handwriting styles) or drawing.

## [Parker jotter](http://www.target.com/p/parker-jotter-stainless-steel-pen/-/A-51938010?ref=tgt_adv_XS000000&AFID=google_pla_df&CPNG=PLA_Seasonal+Shopping&adgroup=SC_Seasonal&LID=700000001170770pgs&network=g&device=c&location=9008336&gclid=Cj0KEQjwuZvIBRD-8Z6B2M2Sy68BEiQAtjYS3LrYsN4c30zMNJojmwdQSjuoJNsxsJhwwWuEXTH1TJ8aAs748P8HAQ&gclsrc=aw.ds)
I use this one for signing documents, and 'regular' writing—notes to myself, etc. It's a fancy ballpoint, basically.
![This is the parker jotter. It is fancy af.](https://cloud.githubusercontent.com/assets/1720093/25580675/bba90af6-2e50-11e7-8e6e-2d0a2943cb26.jpg)
[Relevant](https://twitter.com/helenvholmes/status/695318840163463168)

## [Sakura Pigma FB](https://www.amazon.com/Sakura-50025-Pigma-Professional-2-Pack/dp/B00THY7BGQ)
This is a brush pen, which is great for calligraphy (I use this one when I'm "drawing" letters.
![This is my favorite pen for brush scripts rn.](https://cloud.githubusercontent.com/assets/1720093/25580776/9886910a-2e51-11e7-986e-c53ef23796f5.jpg)
[See this tweet](https://twitter.com/helenvholmes/status/695319247044542464) for some examples of how it writes. I love this pen.

## [Calligraphy stems](https://www.amazon.com/Speedball-Oblique-Point-Holder-ANH9455/dp/B000BYT4FC/ref=sr_1_1?s=office-products&ie=UTF8&qid=1493646052&sr=1-1&keywords=calligraphy+holder)
I don't use these a whole lot these day—I prefer the brush pens above since they're more portable than caring around jars of ink—but using these really helps you get a grasp on the physics of how calligraphy works when you go to draw it later. I still think that it's a beautiful art form and wish I was better at it.
![These you use for actual calligraphy.](https://cloud.githubusercontent.com/assets/1720093/25580908/51df2720-2e52-11e7-9afd-5334fcaeccad.jpg)

## Sharpies
These are a standby, really. Scared of drawing something? Bust out a sharpie. Go to town. Don't be afraid. If anyone asks, you tried to draw the damn thing in sharpie, of course it's a hot mess.

## [Papermate flair M pens](https://www.amazon.com/Paper-Mate-Flair-Medium-12-Count/dp/B0006VO194/ref=sr_1_2?s=office-products&ie=UTF8&qid=1493646236&sr=1-2&keywords=Papermate+flair+M)
I use these pens really frequently (perhaps the most). I have fond memories of drawing with my best friend in elementary school with these pens. They're felt tip, rounded, and get messier over time. I like them because they're similar to microns but without options and cheaper. 
![This is my favorite everyday pen.](https://cloud.githubusercontent.com/assets/1720093/25581000/e7505de2-2e52-11e7-8fc5-d86c568265f2.jpg)
[Link to how they draw](https://twitter.com/helenvholmes/status/695320566161547264)

## [Paint markers](https://www.amazon.com/dp/B000BRFDVS/ref=sxr_rr_xsim1?pf_rd_m=ATVPDKIKX0DER&pf_rd_p=2795440402&pd_rd_wg=haGyH&pf_rd_r=GA791QPMMCTJX4B6HG3R&pf_rd_s=desktop-rhs-carousels&pf_rd_t=301&pd_rd_i=B000BRFDVS&pd_rd_w=CjnVa&pf_rd_i=elmer%27s+paint+pen&pd_rd_r=E4YH93AKKBNY4XRKWK91&ie=UTF8&qid=1493646385&sr=1)
These didn't have a particularly long life, but they were pretty fun. I bought some of these to do a Skillshare class on drawing logos and I love the way they write.
![This is an Elmer's paint marker.](https://cloud.githubusercontent.com/assets/1720093/25581065/6543ff92-2e53-11e7-9398-ee03bbf28e8c.jpg)
[Link to how they draw](https://twitter.com/helenvholmes/status/695320840846471168)

# Paper
I've used all sorts of different notebooks and paper, so these feel like slightly different questions to me. I love suer thick, heavy cardstock for finished work, or anything I'm hoping will be a present for someone—the thicker it feels, the fancier it feels in my opinion.

For notebooks, though, it runs the gambit. I like my paper a little thicker so that sharpies don't bleed through if I can help it but I have rules about finishing each and every notebook I buy, even if the paper in it ain't so great:

![Some of my sketchbooks](https://cloud.githubusercontent.com/assets/1720093/25581134/da41c202-2e53-11e7-8879-1c6862ed3715.JPG)

Lately I've been springing for [Muji sketchbooks](https://www.amazon.com/MUJI-Blank-Notebook-Unruled-30sheets/dp/B00IQQE5EM/ref=sr_1_cc_5?s=aps&ie=UTF8&qid=1493646760&sr=1-5-catcorr&keywords=muji+notebook) because they're so slim and portable, but they're somewhat small and I run through them really quickly, so I'm planning to switch to my old [Moleskine standard](https://www.amazon.com/Moleskine-Cahier-Journal-Extra-Large/dp/8883705033/ref=sr_1_fkmr1_1?s=arts-crafts&ie=UTF8&qid=1493646855&sr=1-1-fkmr1&keywords=moleskine+sketchbook+3+pack) from my school days. A long time ago I would get hard cover sketchbooks, but these days I don't like to carry extra weight on my back if I can help it.

And there you go, a long answer to a short question! Hope ya liked it.
