### ISSUE TITLE
Keys to your success?

### ISSUE THREAD

**Issue by devoidofgenius** [helenvholmes/ama#6]
What do you feel have been the keys to your success? Also, if you could go back and give yourself advice when starting out, what's one thing you would've done and what's one thing you would've avoided?

**Comment by helenvholmes** [comment]
The answer to this question is coming in really late because I thought it merited more thought than a quick answer. For one, I was really hung up on the definition of success and why you think I have it, so I'm going to try and break down some theories for what you might mean by that:

- **Having an audience:** keys to this have been over-using a platform, following people, interacting with them, producing content, trying to be _interesting_, modifying that based on what people seem to react well to.
- **Paying my bills:** keys to this was learning to code, which meant I could pay the bills while my husband was finishing his masters. (Design alone wasn't quite cutting it.)
- **Getting a job (now gigs) in tech:** keys to this were networking, mostly. While I'd love to be grandiose and shoot down nepotism people can't refer you to jobs if no one knows who you are. All of my client work has been through referrals. Cofounding Women Who Code DC helped me meet someone who referred me for my first gig, which then threw me in the path of some other people who helped me get my next one, which helped me meet a ton more people to get me client work now. Conferences were a part of that too.

If I was to formulate that all into a sound bite I'd say "Be here to make friends". (I'm here to make friends, anyway.) While talent and hard work and improving your craft is an important part of that process _to me,_ I am eternally shocked by how much has been possible for me merely because _I was just at the forefront of someone else's mind who thought I would be a good fit for the thing_. 

(Thank you to all those people, you are all wonderful.)

If I could go back:

Hard to say, honestly. I'm pretty content with my life. Parts of it were challenging and stressful and even terrible, but the [learnings were important too](https://helenvholmes.com/writing/2016-in-review). (Every bad job teaches you something, even if it's small.)

If this issue cannot be closed, however, without answering those two questions in their entirety I would say: I would tell previous Helen to always pack sweatpants when traveling despite how much room they take up in ones suitcase, because I always want them, and end up freezing otherwise. (Current Helen is on the edge as to whether or not this advice extends to house slippers too.) Current Helen would also advise previous Helen to avoid dying her hair blonde out of a box from CVS because current, wiser Helen knows that all previous Helen will do is turn her hair orange and end up having to cough up the dough to get it done in a salon anyway. (Oh Helen.)

(And thanks for calling me successful. You're rad, and too kind. 💞)
