### ISSUE TITLE
Where do you want to be? 

### ISSUE THREAD

**Issue by mxstbr** [helenvholmes/ama#8]
What's your big dream, your end goal, the thing you're working towards? 

Feel free to close this if you feel it's too heavy. :blush:

**Comment by helenvholmes** [comment]
Super heavy but also pretty cool, so my answers might seem a little vague.

I quit my job in December last year and started my own business in January. It's really small-scale right now—it's literally just me—but I did it because I wanted to start thinking like a businesswoman instead of like an employee. That means a lot of boring stuff, like filing taxes differently and finding clients and writing contracts and sending bills, which is annoying.

It also has meant long-term planning and imagining projects that bring in money and finding collaborators and thinking objectively and succinctly about where I want my skills and portfolio and business to go. That's been a mindshift that's been really positive and exciting!

All right, so I'm going to split this answer up into a three-parter:

**Where do I want to be in terms of location:** I bring this up because I think location is relevant to a lot of my business and personal goals! I'm moving up to NYC this summer to pursue different kinds of clients and to network. It's kinda weird because I've never moved somewhere as a strategic move before—I've always moved based on circumstance. I'll miss where I currently live but I'm excited for the future too.

**Where do I want my business to be:** I'm meeting with some investors over starting a small physical space that might fizzle out into nothing, but who knows. It's so far from code for me that it's kinda crazy it's happening at all, really. I'm also developing a product with someone that I'm hoping can be sold. We'll see! Those are big goals and they might fail, but being able to sell a product at some point is a big personal goal.

**Where do I want to be:** On a small farm in Virginia wine country with a snowbird location in South America. It'll happen eventually 😌

**Comment by mxstbr** [comment]
Awesome, thanks for the detailed answer. Interesting stuff that's happening, can't wait to see where it goes!
